spring.datasource.url=jdbc:postgresql://db.sslwttanvtrqkjvvnxvy.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=nAefZQy84adyYxfS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true